//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Application.SMService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARRIER", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service")]
    public enum CARRIER : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TMOBILE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPRINT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VERIZON = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATT = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SMS", ReplyAction="http://tempuri.org/IService/SMSResponse")]
        bool SMS(string Gmail_Account, string Password, string Phone, SMS_Application.SMService.CARRIER Provider, string Message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SMS_Application.SMService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SMS_Application.SMService.IService>, SMS_Application.SMService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SMS(string Gmail_Account, string Password, string Phone, SMS_Application.SMService.CARRIER Provider, string Message) {
            return base.Channel.SMS(Gmail_Account, Password, Phone, Provider, Message);
        }
    }
}
